services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=proposta_user
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=proposta_db

    ports:
      - 5432:5432

    volumes:
      - proposta_db_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -u admin -d proposta_db"]
      interval: 5s
      timeout: 5s
      retries: 3

volumes:
  proposta_db_data:

